# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: c7baebb5452d3a15facd541e7392168cabbe91f187467601326d70fbf811da5ba4ab00b8c9031538d0749f88af002627bac56ca47627cf2c1478ffd68c304d0b

test:
  secret_key_base: 5746765699b058208ced5af4d70dc8f0d3957b6237851252da1a00ea3b11e5c9f93cc359a2a29363b96f1d20bc5bfe71c4a61bc7ca991ce2e5d947030233c9d9

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
